# DBT Profiles Configuration for Snowflake DBT Projects
# When running within Snowflake DBT PROJECT objects, authentication is handled automatically

bcs_platform:
  target: dev
  outputs:
    # Development environment
    dev:
      type: snowflake
      account: 'not needed'  # Handled by Snowflake
      user: 'not needed'     # Handled by Snowflake
      role: DBT_DEVELOPER
      database: DB_DEV
      schema: DEV_BRANDON
      warehouse: WH_DBT_DEV
      threads: 2
      
    # Production environment  
    prod:
      type: snowflake
      account: 'not needed'  # Handled by Snowflake
      user: 'not needed'     # Handled by Snowflake
      role: DBT_RUNNER
      database: DB_PROD
      schema: PROD
      warehouse: WH_DBT
      threads: 4